#!/bin/bash

MAX_NUM_OF_THREADS=10
FILE_PATH=randomStrings.txt
temp_filename=symbol_result.tmp

rm -rf $temp_filename

if [ "$1" != "" ]; then MAX_NUM_OF_THREADS=$1
fi

if [ "$2" != "" ]; then FILE_PATH=$2
fi

if [ "$3" != "" ]; then make performance-symbol NUM_OF_THREADS=0 FILE_PATH=$FILE_PATH CC="$3" > $temp_filename
else make performance-symbol NUM_OF_THREADS=0 FILE_PATH=$FILE_PATH > $temp_filename
fi

if [ $MAX_NUM_OF_THREADS -gt 1 ]; then
	for index in $(seq 2 $MAX_NUM_OF_THREADS) ; do
		./run_test $index $FILE_PATH >> $temp_filename
	done
fi

echo "MAX_NUM_OF_THREADS: "MAX_NUM_OF_THREADS

n=1
row=""
echo -e "# of threads\t insert\t\t lookup\t\t resolve"
while read line; do
	function=$(echo $line | cut -d':' -f1)
	if [ "$function" = "insert" ] || [ "$function" = "insertParallel" ]; then
	  row+="$n\t\t"
		row+=$(echo $line | cut -d':' -f2)"\t"
	fi
	if [ "$function" = "lookup" ] || [ "$function" = "lookupParallel" ]; then
		row+=$(echo $line | cut -d':' -f2)"\t"
	fi
	if [ "$function" = "resolve" ] || [ "$function" = "resolveParallel" ]; then
		row+=$(echo $line | cut -d':' -f2)
		echo -e $row
		row=""
		n=$((n+1))
	fi
done < $temp_filename

rm -rf $temp_filename
