#!/bin/bash

args=("$@")
path=$(pwd)
symbol='symbol'
record='record'

function test_symbol() {
	echo "********** Test Symbol Table **********"
	g++-9 -o symbol tests/symbol_table_test.cpp -I $path -I $path/src/include -std=c++17		
	if [ $? == 0 ]; then ./$symbol
		if [ $? == 0 ]; then rm $symbol
		fi
	else echo "Complile Error"
	fi
}

function test_record() {
	echo "********** Test Record Table **********"
	g++-9 -o record tests/record_table_test.cpp -I $path -I $path/src/include -std=c++17
	if [ $? == 0 ]; then ./$record
		if [ $? == 0 ]; then rm $record
		fi
	else echo "Complile Error"
	fi
}


if [ ${#args[@]} == 0 ]; then test_symbol; test_record
else
	for index in ${!args[*]} ; do
		if [ ${args[$index]} == $symbol ]; then test_symbol
		elif [ ${args[$index]} == $record ]; then test_record
		else echo "ERROR: ${args[$index]} is unkown."
		fi
	done
fi
:
